### PR TITLE
chore: upgrade CI OTP and Elixir versions

### PR DESCRIPTION
**Pull request by yordis**
Signed-off-by: Yordis Prieto <yordis.prieto@gmail.com>

### CODE REVIEW

**Comment by yordis** [comment]
@teamon, do you have any clue what the proper fix for the unit test is? I am not sure what route to take.

**Comment by teamon** [comment]
This looks like some issue with httparrot maybe?

**Comment by nathany-copia** [comment]
Looks like we need to give this another try.

@yordis How many versions back do you want to keep in CI? (for Elixir and Erlang/OTP)

**Comment by nathany-copia** [comment]
I'll do up a new PR to update CI

I won't necessarily know what needs to be done to fix failures/warnings in new Elixir versions, but it's a start.

**Comment by nathany-copia** [comment]
Can this be closed now that #682 is merged?

**Comment by yordis** [comment]
I need to follow up on adding `.tool-versions`, or please add it yourself 🙏🏻

**Pull request closed without merging**
