### PR TITLE
fix httpc bodyless methods

### PR DESCRIPTION
**Pull request by olafura**
Currently we are creating a request with body and content_type in many cases for methods that can't support it. Httpc doesn't know what to do an outputs a function match error.

### CODE REVIEW

**Comment by yordis** [comment]
I remember some discussions about it, and I remember something around the point of "HTTP" spec technically allowing a body.

@teamon I am gonna need your help in terms of what we should do here, I feel we should merge it, but still, different clients do different things so a bit tricky.

- https://stackoverflow.com/questions/978061/http-get-with-request-body
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/GET

**Comment by olafura** [comment]
@yordis didn't know before this that GET could contain a body and I used to use telnet to send request for fun.

The reason why I implemented this is because httpc can't contain a body for anything but post, put, patch, and delete.
https://github.com/erlang/otp/blob/40922798411c2d23ee8a99456f96d6637c62b762/lib/inets/src/http_client/httpc.erl#L161

Reading more into the links provided where they mention that servers can reject the request sometimes with the body. It's an edge case but if we really do want to support it we will have to patch httpc to be able to support it.

Reading through the source code of hackney they do seem to support it for some times of body requests but not others.

**Comment by yordis** [comment]
I know you are 100% right on this one, httpc would need to fix their stuff.

So I guess people must be aware of such technicality, otherwise 🤷🏻

**Comment by yordis** [comment]
CI keeps failing 😢

**Comment by olafura** [comment]
Yeah don't know why the tests are trying to access priv directly and not through `:code.priv_dir`

**Comment by olafura** [comment]
I sound really judgemental :grin:, I came to Elixir through Erlang ( was still getting tripped up by it's syntax ). So I've been exposed to a lot of the old best practices.

**Comment by yordis** [comment]
😭

**Comment by olafura** [comment]
There is at least one flaky test

**Comment by yordis** [comment]
I remember something about a flaky test for sure!

**Review by yordis — APPROVED** [review]

**Pull request merged**
