### PR TITLE
fix: use mint passive mode

### LINKED ISSUE #509: Mint passive mode
## tl;dr

Switch `Tesla.Adapter.Mint` to use passive mode, as suggesting in https://github.com/teamon/tesla/issues/357#issuecomment-916967770

## (Potentially) related issues:
- https://github.com/teamon/tesla/issues/357
- https://github.com/teamon/tesla/issues/450
- https://github.com/teamon/tesla/issues/394
- https://github.com/teamon/tesla/issues/385
- https://github.com/teamon/tesla/issues/370

### PR DESCRIPTION
**Pull request by yordis**
closes #509

### CODE REVIEW

**Comment by yordis** [comment]
@ericmj @teamon all the tests are passing, so I am not sure if I should add a new test case or anything else to make sure this works.

Would appreciate some support over here! 🙏🏻

**Comment by yordis** [comment]
hah? all tests pass locally but failed in CI 😭

**Comment by ericmj** [comment]
Might be a good to change these tests to use active mode since you changed the default: https://github.com/elixir-tesla/tesla/blob/master/test/tesla/adapter/mint_test.exs#L83.

Other than that I am not sure what I can help with?

**Comment by yordis** [comment]
hah, which leads me to a question, should I allow users to change this? Like should I use `Map.put_new` instead?

**Comment by ericmj** [comment]
I don't see a reason why you would want active mode with with how tesla uses mint but I don't understand why you would want tesla to create the connection so there may be use cases I am missing.

But I don't think it hurts to leave it as an option with the default being passive mode.

**Pull request merged**
