### PR TITLE
Upgrade httparrot to 1.4.0

### LINKED ISSUE #684: Test failures and compiler warnings in Elixir 1.16 (httparrot)
There are quite a few test failures and warnings in Elixir 1.16.

The test failures are related to httparrot not yet supporting newer versions of Elixir.
https://github.com/edgurgel/httparrot/issues/38

It looks like the old version of cowboy is also getting brought in via httparrot.

Example CI run: https://github.com/elixir-tesla/tesla/actions/runs/9587197853/job/26436887009

### PR DESCRIPTION
**Pull request by nathany-copia**
closes #684

### CODE REVIEW

**Review by yordis — APPROVED** [review]
I want to cry right now 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭 😭

**Comment by nathany-copia** [comment]
tears of joy?

**Comment by yordis** [comment]
> tears of joy?

Both, joy and pain!

**Comment by nathany-copia** [comment]
Thanks @yordis.

It's very nice that we can run the test suite with a recent version of Elixir now. 
Makes it easier to contribute in the future.

**Pull request merged**
