### PR TITLE
feat: allow to configure the prefix for the telemtry events

### PR DESCRIPTION
**Pull request by yordis**
Recently, @seancribbs asked to be able to control the prefix.

What is the proper solution here?

1. Allow people to customize the prefix
2. Hook into the events and, based on the data, do something with it, such as using the HOST information of the request or User-Agent
3. ?????

### CODE REVIEW

**Comment by bryannaegele** [comment]
Other libraries allow this (plug.telemetry, ecto, etc). 👍🏻

**Comment by teamon** [comment]
@yordis Please take a look https://github.com/elixir-tesla/tesla/pull/390#issuecomment-644243214

**Comment by bryannaegele** [comment]
Yeah, I misspoke here in this PR. Sorry. They can key off something in the metadata. We do need the event name to be consistent.

If it isn't already possible, if the user can apply some metadata to the event then it could be trivial to figure out which client it's coming from.

**Comment by teamon** [comment]
That's why I'm referencing this comment, I don't see the need to change the prefix (and IMO it will cause more harm than good)

**Comment by bryannaegele** [comment]
@yordis can you please revert?

**Comment by yordis** [comment]
oooopppppsss sorry! 😭 😭 😭 😭 😭 😭

**Pull request merged**
